export {
  IconSlash,
  IconPlus,
  IconSearch,
  IconMore,
  IconFolder,
  IconPage,
  IconInbox,
  IconDrafts,
  IconReviews,
  IconBranch,
  IconUnfold,
  IconExpandAll,
  IconCollapseAll,
  IconHistory,
  IconChat,
  IconSparkles,
  IconMerge,
  IconBringChanges,
  IconArrowUp,
  IconClose,
  IconImage,
  IconTrash,
  IconDice,
  IconPanel,
  IconWorkPane,
  IconDiscard,
  IconCheck,
  IconCheckCircle,
  IconTemplateBlank,
  IconTemplateMeeting,
  IconTemplateTasks,
  IconTemplateProject,
  IconTemplateNotes,
  IconTemplateDecision,
  type IconProps,
} from "./Icons";
