export type EmojiItem = {
  glyph: string;
  name: string;
};

export type EmojiCategory = {
  id: string;
  label: string;
  hint: string;
  items: EmojiItem[];
};

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "docs",
    label: "Docs",
    hint: "📝",
    items: [
      { glyph: "📝", name: "memo note nota" },
      { glyph: "📄", name: "page document pagina" },
      { glyph: "📑", name: "bookmark tabs" },
      { glyph: "📚", name: "books libros" },
      { glyph: "📖", name: "open book" },
      { glyph: "📌", name: "pin chincheta" },
      { glyph: "📍", name: "round pin" },
      { glyph: "💡", name: "idea bulb idea" },
      { glyph: "⚡", name: "zap lightning rayo" },
      { glyph: "🎯", name: "target objetivo" },
      { glyph: "🚀", name: "rocket cohete launch" },
      { glyph: "⚠️", name: "warning alerta" },
      { glyph: "✅", name: "check done listo" },
      { glyph: "❌", name: "cross no" },
      { glyph: "💬", name: "speech comment comentario" },
      { glyph: "💭", name: "thought" },
      { glyph: "🔗", name: "link enlace" },
      { glyph: "🗂️", name: "dividers" },
      { glyph: "📁", name: "folder carpeta" },
      { glyph: "📂", name: "open folder" },
      { glyph: "🏷️", name: "label etiqueta" },
      { glyph: "🧭", name: "compass navegacion" },
      { glyph: "🗺️", name: "map mapa" },
      { glyph: "🧪", name: "test tube prueba" },
      { glyph: "🐛", name: "bug" },
      { glyph: "🛠️", name: "tools herramientas" },
      { glyph: "⚙️", name: "gear settings" },
      { glyph: "🔒", name: "lock privado" },
      { glyph: "🔑", name: "key llave" },
      { glyph: "📊", name: "bar chart metricas" },
      { glyph: "📈", name: "chart up" },
      { glyph: "📉", name: "chart down" },
      { glyph: "🧩", name: "puzzle" },
      { glyph: "🧱", name: "brick" },
      { glyph: "🗓️", name: "calendar calendario" },
      { glyph: "⏰", name: "alarm" },
      { glyph: "⏳", name: "hourglass" },
      { glyph: "📦", name: "package" },
      { glyph: "🚢", name: "ship" },
      { glyph: "🧠", name: "brain" },
      { glyph: "🔍", name: "search buscar" },
      { glyph: "📣", name: "megaphone anuncio" },
    ],
  },
  {
    id: "smileys",
    label: "Smileys",
    hint: "😀",
    items: [
      { glyph: "😀", name: "grin" },
      { glyph: "😃", name: "smiley" },
      { glyph: "😄", name: "smile" },
      { glyph: "😁", name: "beam" },
      { glyph: "😅", name: "sweat smile" },
      { glyph: "😂", name: "joy" },
      { glyph: "🙂", name: "slight smile" },
      { glyph: "😉", name: "wink" },
      { glyph: "😊", name: "blush" },
      { glyph: "😍", name: "heart eyes" },
      { glyph: "🤩", name: "star struck" },
      { glyph: "😎", name: "cool" },
      { glyph: "🤔", name: "thinking pensar" },
      { glyph: "🤗", name: "hug" },
      { glyph: "🫡", name: "salute" },
      { glyph: "🤫", name: "shush" },
      { glyph: "😶", name: "no mouth" },
      { glyph: "😐", name: "neutral" },
      { glyph: "🙄", name: "eyeroll" },
      { glyph: "😴", name: "sleep" },
      { glyph: "🥳", name: "party" },
      { glyph: "🤯", name: "exploding" },
      { glyph: "😤", name: "steam" },
      { glyph: "😡", name: "angry" },
      { glyph: "😢", name: "cry" },
      { glyph: "🥺", name: "pleading" },
      { glyph: "😱", name: "scream" },
      { glyph: "🤓", name: "nerd" },
      { glyph: "👻", name: "ghost" },
      { glyph: "🤖", name: "robot" },
      { glyph: "👍", name: "thumbs up" },
      { glyph: "👎", name: "thumbs down" },
      { glyph: "👏", name: "clap" },
      { glyph: "🙌", name: "raised hands" },
      { glyph: "🙏", name: "pray thanks" },
      { glyph: "💪", name: "muscle" },
      { glyph: "✌️", name: "victory" },
      { glyph: "🤞", name: "cross fingers" },
      { glyph: "👋", name: "wave" },
    ],
  },
  {
    id: "hearts",
    label: "Hearts",
    hint: "❤️",
    items: [
      { glyph: "❤️", name: "red heart" },
      { glyph: "🧡", name: "orange heart" },
      { glyph: "💛", name: "yellow heart" },
      { glyph: "💚", name: "green heart" },
      { glyph: "💙", name: "blue heart" },
      { glyph: "💜", name: "purple heart" },
      { glyph: "🖤", name: "black heart" },
      { glyph: "🤍", name: "white heart" },
      { glyph: "🤎", name: "brown heart" },
      { glyph: "💔", name: "broken heart" },
      { glyph: "💕", name: "two hearts" },
      { glyph: "💖", name: "sparkling heart" },
      { glyph: "✨", name: "sparkles" },
      { glyph: "⭐", name: "star estrella" },
      { glyph: "🌟", name: "glowing star" },
      { glyph: "🔥", name: "fire fuego" },
      { glyph: "💯", name: "hundred" },
      { glyph: "🎉", name: "tada" },
      { glyph: "🎊", name: "confetti" },
    ],
  },
  {
    id: "nature",
    label: "Nature",
    hint: "🌿",
    items: [
      { glyph: "🌱", name: "seedling" },
      { glyph: "🌿", name: "herb" },
      { glyph: "🍀", name: "clover" },
      { glyph: "🌸", name: "cherry blossom" },
      { glyph: "🌺", name: "hibiscus" },
      { glyph: "🌻", name: "sunflower" },
      { glyph: "🌳", name: "tree" },
      { glyph: "🌲", name: "evergreen" },
      { glyph: "🌙", name: "moon" },
      { glyph: "☀️", name: "sun" },
      { glyph: "☁️", name: "cloud" },
      { glyph: "❄️", name: "snowflake" },
      { glyph: "🌈", name: "rainbow" },
      { glyph: "🌊", name: "wave" },
      { glyph: "🐶", name: "dog" },
      { glyph: "🐱", name: "cat" },
      { glyph: "🐭", name: "mouse" },
      { glyph: "🦊", name: "fox" },
      { glyph: "🐻", name: "bear" },
      { glyph: "🐼", name: "panda" },
      { glyph: "🐨", name: "koala" },
      { glyph: "🦁", name: "lion" },
      { glyph: "🐸", name: "frog" },
      { glyph: "🐝", name: "bee" },
      { glyph: "🦋", name: "butterfly" },
      { glyph: "🐢", name: "turtle" },
      { glyph: "🐙", name: "octopus" },
    ],
  },
  {
    id: "food",
    label: "Food",
    hint: "🍎",
    items: [
      { glyph: "🍏", name: "green apple" },
      { glyph: "🍎", name: "red apple" },
      { glyph: "🍊", name: "orange" },
      { glyph: "🍋", name: "lemon" },
      { glyph: "🍌", name: "banana" },
      { glyph: "🍉", name: "watermelon" },
      { glyph: "🍇", name: "grapes" },
      { glyph: "🍓", name: "strawberry" },
      { glyph: "🥑", name: "avocado" },
      { glyph: "🌶️", name: "pepper" },
      { glyph: "🍞", name: "bread" },
      { glyph: "🧀", name: "cheese" },
      { glyph: "🍕", name: "pizza" },
      { glyph: "🍔", name: "burger" },
      { glyph: "🌮", name: "taco" },
      { glyph: "🍣", name: "sushi" },
      { glyph: "🍪", name: "cookie" },
      { glyph: "🎂", name: "cake" },
      { glyph: "☕", name: "coffee cafe" },
      { glyph: "🍵", name: "tea" },
      { glyph: "🍺", name: "beer" },
      { glyph: "🍷", name: "wine" },
    ],
  },
  {
    id: "travel",
    label: "Travel",
    hint: "✈️",
    items: [
      { glyph: "🏠", name: "house casa" },
      { glyph: "🏢", name: "office" },
      { glyph: "🏫", name: "school" },
      { glyph: "🏥", name: "hospital" },
      { glyph: "🏦", name: "bank" },
      { glyph: "🏰", name: "castle" },
      { glyph: "✈️", name: "plane avion" },
      { glyph: "🚗", name: "car" },
      { glyph: "🚌", name: "bus" },
      { glyph: "🚂", name: "train" },
      { glyph: "🚲", name: "bike" },
      { glyph: "⛵", name: "sailboat" },
      { glyph: "🌍", name: "globe europe" },
      { glyph: "🌎", name: "globe americas" },
      { glyph: "🌏", name: "globe asia" },
      { glyph: "⛰️", name: "mountain" },
      { glyph: "🏕️", name: "camping" },
      { glyph: "🏖️", name: "beach" },
    ],
  },
  {
    id: "objects",
    label: "Objects",
    hint: "📎",
    items: [
      { glyph: "💻", name: "laptop" },
      { glyph: "🖥️", name: "desktop" },
      { glyph: "📱", name: "phone" },
      { glyph: "⌨️", name: "keyboard" },
      { glyph: "🖱️", name: "mouse" },
      { glyph: "🖨️", name: "printer" },
      { glyph: "📷", name: "camera" },
      { glyph: "🎥", name: "movie" },
      { glyph: "🎤", name: "mic" },
      { glyph: "🎧", name: "headphones" },
      { glyph: "🔔", name: "bell" },
      { glyph: "📎", name: "paperclip" },
      { glyph: "✂️", name: "scissors" },
      { glyph: "📐", name: "triangle ruler" },
      { glyph: "🖊️", name: "pen" },
      { glyph: "✏️", name: "pencil" },
      { glyph: "💰", name: "money bag" },
      { glyph: "💳", name: "card" },
      { glyph: "💎", name: "gem" },
      { glyph: "🎁", name: "gift" },
      { glyph: "🏆", name: "trophy" },
      { glyph: "🥇", name: "gold" },
      { glyph: "🎮", name: "game" },
      { glyph: "🎲", name: "dice" },
      { glyph: "🧩", name: "puzzle piece" },
      { glyph: "🛡️", name: "shield" },
      { glyph: "⚖️", name: "scales" },
      { glyph: "🧹", name: "broom" },
      { glyph: "🪄", name: "wand" },
      { glyph: "🧿", name: "nazar" },
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    hint: "🔵",
    items: [
      { glyph: "🔴", name: "red circle" },
      { glyph: "🟠", name: "orange circle" },
      { glyph: "🟡", name: "yellow circle" },
      { glyph: "🟢", name: "green circle" },
      { glyph: "🔵", name: "blue circle" },
      { glyph: "🟣", name: "purple circle" },
      { glyph: "⚫", name: "black circle" },
      { glyph: "⚪", name: "white circle" },
      { glyph: "🟥", name: "red square" },
      { glyph: "🟧", name: "orange square" },
      { glyph: "🟨", name: "yellow square" },
      { glyph: "🟩", name: "green square" },
      { glyph: "🟦", name: "blue square" },
      { glyph: "🟪", name: "purple square" },
      { glyph: "⬛", name: "black square" },
      { glyph: "⬜", name: "white square" },
      { glyph: "🔶", name: "orange diamond" },
      { glyph: "🔷", name: "blue diamond" },
      { glyph: "➡️", name: "right arrow" },
      { glyph: "⬅️", name: "left arrow" },
      { glyph: "⬆️", name: "up arrow" },
      { glyph: "⬇️", name: "down arrow" },
      { glyph: "↩️", name: "return" },
      { glyph: "✳️", name: "eight spoked" },
      { glyph: "❇️", name: "sparkle" },
      { glyph: "❓", name: "question" },
      { glyph: "❗", name: "exclaim" },
      { glyph: "💤", name: "zzz" },
    ],
  },
];

export function allEmojiItems(): EmojiItem[] {
  return EMOJI_CATEGORIES.flatMap((cat) => cat.items);
}

export function filterEmoji(query: string): EmojiItem[] {
  const q = query.trim().toLowerCase();
  if (!q) {
    return allEmojiItems();
  }
  return allEmojiItems().filter(
    (item) => item.glyph.includes(q) || item.name.toLowerCase().includes(q),
  );
}
